import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavbarMobile from "../components/Navbar/NavbarMobile";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative m-auto">
        <div className="max-w-4xl m-auto">
          <NavbarMobile />
          <div className="relative top-20">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam fuga
            ab dolores quos harum blanditiis dolor, esse reiciendis, provident
            doloremque totam, officia nisi ipsa. Natus placeat recusandae libero
            explicabo odit! Lorem ipsum dolor, sit amet consectetur adipisicing
            elit. Ipsam fuga ab dolores quos harum blanditiis dolor, esse
            reiciendis, provident doloremque totam, officia nisi ipsa. Natus
            placeat recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Ipsam fuga ab dolores quos harum
            blanditiis dolor, esse reiciendis, provident doloremque totam,
            officia nisi ipsa. Natus placeat recusandae libero explicabo
            odit!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam
            fuga ab dolores quos harum blanditiis dolor, esse reiciendis,
            provident doloremque totam, officia nisi ipsa. Natus placeat
            recusandae libero explicabo odit!
          </div>
        </div>
      </main>
    </div>
  );
}
