import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Button from "../components/Buttons/Button";
import Card from "../components/Card/Card";
import Footer from "../components/Footer/Footer";
import NavbarDesktop from "../components/Navbar/NavbarDesktop";
import NavbarMobile from "../components/Navbar/NavbarMobile";
import Timeline from "../components/Timeline/Timeline";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="h-fit">
        <NavbarMobile />
        <div className="px-4 lg:px-0 max-w-4xl m-auto">
          <NavbarDesktop />
          <div className="pt-16 m-auto">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt rem
            nobis iusto nulla repudiandae ipsum! Nesciunt rerum ratione
            voluptatem, velit at aliquid nisi distinctio sapiente fugiat? Hic
            fugiat assumenda exercitationem!
          </div>
          <Timeline />
          <div className="flex flex-wrap">
            <Card />
            <Card />
          </div>
          <div>
            <Button>Visit Site</Button>
          </div>
          <Footer />
        </div>
      </main>
    </div>
  );
}
